CREATE TABLE radna_db.journal_entry (
	id UUID DEFAULT gen_random_uuid() NOT NULL,
    transaction_id VARCHAR(30) NOT NULL,
    transaction_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    account_number VARCHAR(30) NOT NULL,
    entry_type VARCHAR(12) NOT NULL,
    description VARCHAR(50) NOT NULL,
    amount FLOAT NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    posting_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(15) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);