UTF_8 = "utf-8"

POST_METHOD = "POST"
GET_METHOD = "GET"
PUT_METHOD = "PUT"
DELETE_METHOD = "DELETE"

REQUEST_REFERENCE_NUMBER = "Request-Reference-Number"

OK_RESPONSE_CODE = 200
CREATED_RESPONSE_CODE = 201